# Generated by Django 4.1.3 on 2023-01-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Reliance Jio', 'Reliance Jio'), ('Airtel', 'Airtel'), ('Vi', 'Vi'), ('BSNL', 'BSNL')], max_length=50)),
                ('owenership', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
