# Generated by Django 4.1.3 on 2023-01-09 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plan', models.CharField(max_length=50)),
                ('validity', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('Preapaid', 'Prepaid'), ('Postpaid', 'Postpaid')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planapi.company')),
            ],
        ),
    ]
